version: "3.9"
services:
    web:
        build: web
        restart: on-failure
    api:
        build: api
        restart: on-failure
        links:
            - mongodb
    mongodb:
        image: mongo
        restart: on-failure
    mongo-seed:
        build: ./mongo-seed
        links:
            - mongodb
    gateway:
        build: gateway
        restart: on-failure
        ports: 
            - "80:80"
        links:
            - web
            - api
