version: "3.9"
services:
    api:
        build: api
        restart: on-failure
        links:
            - mongodb
        ports:
            - "80:80"
    mongodb:
        image: mongo
        # ports:
            # - "27017:27017"
        restart: on-failure
    mongo-seed:
        build: ./mongo-seed
        links:
            - mongodb
